SELECT ORDER_DATE, SUM(REVENUE) OVER (ORDER BY ORDER_DATE) AS CUMMULATIVE_REVENUE 
FROM (SELECT ORDERS.ORDER_DATE, SUM(ORDER_DETAILS.QUANTITY * PIZZAS.PRICE) AS REVENUE 
FROM ORDER_DETAILS JOIN PIZZAS ON ORDER_DETAILS.PIZZA_ID= PIZZAS.PIZZA_ID JOIN ORDERS ON ORDERS.ORDER_ID = ORDER_DETAILS.ORDER_ID 
GROUP BY ORDERS.ORDER_DATE) AS SALES;
