
SELECT 
    ROUND(AVG(TOTAL_ORDERS), 0)
FROM
    (SELECT 
        ORDERS.ORDER_DATE,
            SUM(ORDER_DETAILS.QUANTITY) AS TOTAL_ORDERS
    FROM
        ORDERS
    JOIN ORDER_DETAILS ON ORDERS.ORDER_ID = ORDER_DETAILS.ORDER_ID
    GROUP BY ORDERS.ORDER_DATE) AS ORDER_TOTAL;